[package]
authors = ["Fabrice Le Fessant <fabrice.le_fessant@origin-labs.com>"]
copyright = "OCamlPro SAS & Origin Labs SAS"
dir = "src"
edition = "4.10.0"
github-organization = "ocamlpro"
kind = "library"
license = "LGPL2"
min-edition = "4.03.0"
mode = "binary"
name = "ez_file"
synopsis = "Easy file manipulation (read_file, write_file, etc.)"
version = "0.1.0"

# keys that you could also define:
# dev-repo = "...dev-repo..."
# bug-reports = "...bug-reports..."
# doc-api = "...doc-api..."
# doc-gen = "...doc-gen..."
# homepage = "...homepage..."

[package]
description = """
This library provides some modules to read and write files, and create 
and scan directories.
"""

[drom]
skip = ""

[dependencies]
ocplib_stuff = "0.1.0"
re = "1.0.0"
base-unix = "base unix"

[tools]
dune = "2.6.0"

[package]
wrapped = false
pack = "EzFile"


